DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS game_qa CASCADE;
DROP TABLE IF EXISTS game_cat CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS player CASCADE;

CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY,
    name VARCHAR (100) NOT NULL,
    age INTEGER NULL DEFAULT NULL,
    email VARCHAR (100) NULL DEFAULT NULL,
    wins INTEGER NOT NULL DEFAULT 0,
    admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS game (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    creator VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    winner VARCHAR(100) NULL DEFAULT NULL,
    sample BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS game_cat (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    game_id INTEGER REFERENCES game (id)
);

CREATE TABLE IF NOT EXISTS game_qa (
    id SERIAL PRIMARY KEY,
    points INTEGER NOT NULL,
    answer TEXT NOT NULL,
    question VARCHAR(480) NOT NULL,
    double BOOLEAN NOT NULL DEFAULT FALSE,
    category_id INTEGER REFERENCES game_cat (id),
    game_id INTEGER REFERENCES game (id)
);

CREATE TABLE IF NOT EXISTS game_player (
    id SERIAL PRIMARY KEY,
    points INTEGER NOT NULL DEFAULT 0,
    name_id INTEGER REFERENCES account (id),
    game_id INTEGER REFERENCES game (id)
);
